### ISSUE TITLE
Article Section Revamping

### ISSUE THREAD

**Issue by Souhaib-Benbouzid** [dzcode-io/dzcode.io#215]
- [x] Hide articles list on articles page
- [x] create  articles grid view in articles page
- [ ] ~add article pagination~
- [x] add article contributors ( #245 #260 )

**Comment by ZibanPirate** [comment]
closing as done, the `add article pagination` is not needed for now
