### ISSUE TITLE
Search functionality

### ISSUE THREAD

**Issue by souhaib-benbouzid** [dzcode-io/dzcode.io#216]
implement website search functionality

- [x] Setup search backend: #617 
- [x] Indexing models into search backend every 15 mins: #620 
- [x] Search endpoint to be used later by frontend: #623 
- [x] global search from frontend by calling search endpoint: #624

**Comment by NurElHuda** [comment]
This one is linked to #156 and #203 

Does each one has different meaning? or are they duplicates?

**Comment by omdxp** [comment]
What happened to this?

**Comment by ZibanPirate** [comment]
@omdxp started on working on this.

summary:
- will have a search engine as a docker image (already done in #617)
- api will talk to the search engine to ingest data into it and query them
- frontend will have a global search component that calls api, and show results from all models (contributors, contributions, projects)
- result will compose of search items, each will have a title, and url, eg: `name: "Assem Ch", url: "https://www.dzcode.io/team/github-assem-ch"`

check our Discord Server for more

**Comment by omdxp** [comment]
Closing this as it's implemented
