### ISSUE TITLE
Implement localization for `./web`

### ISSUE THREAD

**Issue by ZibanPirate** [dzcode-io/dzcode.io#24]
As a user, I should easily switch to either En, Ar, or Fr on any link in dzcode.io to Social Media, and see content in the respective language.

Tasks:
- [x] Add language changing option to All dzcode.io pages ( #269 )
- [x] Add RTL support ( #270 )
- [x] Handle Urls in multi-language. (#396 and #390  )
- [x] refactor data folder to support multi-language content  (#403  )
- [x] translate the static website content `./web` (#420 )
- [ ] #465

**Feature Branch** : [`feat/localization`](https://github.com/dzcode-io/dzcode.io/tree/feat/localization)
**Feature PR** :  #275

**Comment by abderrahmaneMustapha** [comment]
@ZibanPirate  i think that this is done  "Handle Urls in multi-language."

**Comment by ZibanPirate** [comment]
will merge this one to `main` and continue working there
