### ISSUE TITLE
Add automatic runtime prop-types validation with Typescript

### ISSUE THREAD

**Issue by souhaib-benbouzid** [dzcode-io/dzcode.io#343]
**Description**

typescript provide a great compile time type checking yet it fails when it comes to runtime. babel-plugin-typescript-to-proptypes
 package provide an integration for  typescript to use prop-types packages to do runtime validation.

**Check List**

1. [x] Add the plug-in to `./web` and remove all effected code #344
2. [x] disable 'react/prop-types' eslint rule in `./web` #344
3. [x] Add the plug-in to `./mobile` and remove all effected code #347
4. [x] disable 'react/prop-types' eslint rule in `./mobile` #347
4. [ ] write a reverse 'react/prop-types' lint rule and use it to ensure we don't unnecessarily validate props
5. [ ] create an article on how to automatically validate runtime prop-types in typescript
