### ISSUE TITLE
Use an opensource solution for Error Logging

### ISSUE THREAD

**Issue by ZibanPirate** [dzcode-io/dzcode.io#351]
**Description**

Use an opensource solution for Error Logging for the entire dzcode stack

**Check List**

1. [x] setup error logging on `web` ( #352 )
2. [x] setup error logging on `api`  ( #354 )
3. [ ] setup error logging on `mobile` ( #353 )

**Additional Comments**

sentry.io looks like an open-source friendly solution
